config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-out', to: 'authentication#destroy'
  get 'sign-in', to: 'authentication#new'
  post 'sign-in', to: 'authentication#create'

  get '/tasks/today', to: 'tasks#today', as: :tasks_today

  resources :tasks, only: [:index, :show, :new, :create]
  resources :users, only: [:show]

end

app/models/category.rb
class Category < ActiveRecord::Base

  
end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :user
  belongs_to :category
  belongs_to :task_date

end

app/models/task_date.rb
class TaskDate < ActiveRecord::Base

  has_many :tasks

  def pretty_date
    self.date.strftime("%a %B %e %Y")
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :tasks
  has_many :categories

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :todays_tasks
  before_action :require_login
  before_action :user_cats

  helper_method :current_user

  def todays_tasks
    if current_user
      @todays_tasks = Task.all.where(task_date_id: TaskDate.find_by(date: Date.today.beginning_of_day).id)
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_login
    unless current_user
      session[:previous_url] = request.url
      flash[:error] = "You must sign in"
      redirect_to sign_in_path # halts request cycle
    end
  end

  def user_cats
    if current_user
      @user_cats = Category.where(user_id: [@current_user.id, nil])
    end
  end


end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  skip_before_action :require_login

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You're now logged in! WOO!"
      redirect_to session[:previous_url] || tasks_path
    else
      flash[:error] = "Oops, your username or password is not in our database. Please try again."
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "You're now logged out. See ya next time!"
    redirect_to root_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :require_login

  def index

  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  skip_before_action :require_login

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Yay, you signed up!"
      redirect_to tasks_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def today
  end

  def index
    @tasks = Task.where(user_id: @current_user.id)
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params.merge(user_id: @current_user.id))
    if @task.save
      flash[:notice] = "New practice assignment created successfully!"
      redirect_to tasks_path
    else
      render :new
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :category_id, :task_date_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<%= form_tag sign_in_path do %>
  <%= label_tag :email %>
  <%= text_field_tag :email %>
  <br>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <br>
  <%= submit_tag "Sign In" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PracticeManagerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <% if current_user %>
          <%= link_to "Practice Manager", tasks_path, class: "navbar-brand" %>
        <% else %>
          <%= link_to "Practice Manager", root_path, class: "navbar-brand" %>
        <% end %>
      </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if current_user %>
            <li><%= link_to "Today's Practice", tasks_today_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Areas of Focus <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                  <% @user_cats.each do |cats| %>
                    <li><%= link_to "#{cats.name}" %></li>
                  <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
        <% if current_user %>
          <p class="navbar-text navbar-right"><%= link_to "Sign Out", sign_out_path, class: "navbar-link" %></p>
          <p class="navbar-text navbar-right"><%= link_to "Signed in as #{current_user.email}", user_path(current_user), class: "navbar-link" %></p>
        <% else %>
          <p class="navbar-text navbar-right"><%= link_to "Sign Up", sign_up_path, class: "navbar-link" %></p>
          <p class="navbar-text navbar-right"><%= link_to "Sign In", sign_in_path, class: "navbar-link" %></p>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <div class="container">

    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:error] %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:error] %>
      </div>
    <% end %>

    <%= yield %>

  </div>



</body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to the Practice Manager!</h1>

<p>
  Sign up for an account, where you can create practice tasks and view them by date, area of focus, or musical work. Record clips of your practice session and save them, so that you can track your progress. Create your own categories as well!
</p>

app/views/tasks/index.html.erb
HIIIIIIIII

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <%= f.label :category_id, "Area of Focus" %>
  <%= f.collection_select(:category_id, Category.where(user_id: [@current_user.id, nil]), :id, :name) %>
  <br>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :task_date_id, "Assigned to date" %>
  <%= f.collection_select(:task_date_id, TaskDate.where(date: Date.today.beginning_of_day..2.weeks.from_now.beginning_of_day), :id, :pretty_date) %>
  <br>
  <%= f.submit "Whoosh!" %>
<% end %>

<!-- TaskDate.find(2).date.strftime("%a %B %e %Y") -->

app/views/tasks/today.html.erb
<div class="page-header">
  <h1>Today's Practice Assignments</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Practice Assignment</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <% @todays_tasks.each do |task| %>
      <tr>
        <td><%= link_to task.title, task_path(task) %></td>
        <td><%= task.task_date.pretty_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Practice Assignment", new_task_path %>